# Generated by Django 2.1.1 on 2018-10-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='해당 데이터가 작성된 날짜')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='해당 데이터가 수정된 날짜')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('pg_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('payment_id',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='payments.Payment')),
                ('account_num', models.CharField(max_length=100)),
                ('bank_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='NaverPayPayment',
            fields=[
                ('payment_id',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='payments.Payment')),
                ('naver_email', models.CharField(help_text='결제한 네이버 페이 계정', max_length=100)),
                ('n_pay_payment_id', models.CharField(help_text='네이버 페이쪽 결제내역 id', max_length=100)),
                ('n_pay_used_payment_method', models.CharField(help_text='네이버 페이쪽에서 결제 방식', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment', models.Model),
        ),
    ]
