# Generated by Django 2.1.1 on 2018-09-17 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('pg_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('payment_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='payments.Payment')),
                ('account_num', models.CharField(max_length=100)),
                ('bank_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment',),
        ),
    ]
