# Generated by Django 2.1.1 on 2018-10-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='해당 데이터가 작성된 날짜')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='해당 데이터가 수정된 날짜')),
                ('text', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
