# Generated by Django 2.1.1 on 2018-10-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi_text1', models.CharField(max_length=100)),
                ('hi_text2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='test_b_s',
            field=models.ManyToManyField(blank=True, to='payments.TestB'),
        ),
    ]
