# Generated by Django 2.1.1 on 2018-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0003_auto_20181019_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('test_b_s', models.ManyToManyField(blank=True, to='payments.TestB')),
            ],
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='test_b_s',
        ),
    ]
