# Generated by Django 2.1.1 on 2018-10-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0004_auto_20181019_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testa',
            name='test_b_s',
        ),
        migrations.AddField(
            model_name='testa',
            name='test_b_set',
            field=models.ManyToManyField(blank=True, related_name='test_b_s', related_query_name='test_b_s',
                                         to='payments.TestB'),
        ),
    ]
