# Generated by Django 2.1.1 on 2018-10-11 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_auto_20181011_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodoption',
            name='related_food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='foodoption_food_options', to='product.Food'),
        ),
    ]
