# Generated by Django 2.1.1 on 2018-10-16 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_auto_20181011_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_var', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo_var', models.ManyToManyField(to='product.Bar')),
            ],
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='related_food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='product_foodoption_set', related_query_name='product_foodoption',
                                    to='product.Food'),
        ),
    ]
