# Generated by Django 2.1.1 on 2018-10-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_auto_20181016_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='ex_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foo',
            name='foo_var',
            field=models.ManyToManyField(blank=True, to='product.Bar'),
        ),
    ]
