# Generated by Django 2.1.1 on 2018-10-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='해당 데이터가 작성된 날짜')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='해당 데이터가 수정된 날짜')),
                ('account_owned_order',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='member.Account')),
                (
                'owned_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
