# Generated by Django 2.1.1 on 2018-10-11 06:26

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True,
                                                                    default=django.utils.timezone.now,
                                                                    verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='descriptions',
            field=models.CharField(default='no description Contents', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
